# Generated by Django 5.1.2 on 2024-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField()),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('max_tokens', models.IntegerField(default=150)),
                ('temperature', models.FloatField(default=0.7)),
            ],
        ),
    ]
